# Generated by Django 3.2.13 on 2024-01-09 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wv_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttractionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileAttraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='review',
            name='attraction',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='attraction',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='profile',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password_hash',
            new_name='auth_id',
        ),
        migrations.RemoveField(
            model_name='attraction',
            name='category',
        ),
        migrations.AddField(
            model_name='attraction',
            name='scores',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='scores',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attraction',
            name='image_url',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='UserPreference',
        ),
        migrations.AddField(
            model_name='profileattraction',
            name='attraction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wv_app.attraction'),
        ),
        migrations.AddField(
            model_name='profileattraction',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wv_app.profile'),
        ),
        migrations.AddField(
            model_name='attractiontag',
            name='attraction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wv_app.attraction'),
        ),
        migrations.AddField(
            model_name='attractiontag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wv_app.tag'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='tags',
            field=models.ManyToManyField(related_name='attractions', to='wv_app.Tag'),
        ),
        migrations.AddField(
            model_name='profile',
            name='negative_tags',
            field=models.ManyToManyField(related_name='negative_profiles', to='wv_app.Tag'),
        ),
        migrations.AddField(
            model_name='profile',
            name='positive_tags',
            field=models.ManyToManyField(related_name='positive_profiles', to='wv_app.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='profileattraction',
            unique_together={('profile', 'attraction')},
        ),
        migrations.AlterUniqueTogether(
            name='attractiontag',
            unique_together={('attraction', 'tag')},
        ),
    ]
